post https://aula-python-fiap-default-rtdb.firebaseio.com/contatos.json HTTP/1.1
Content-Type: application/json

{
    "Nome":"Joao Silva",
    "Email":"joao@teste.com",
    "telefone": "(11) 1111-1111"
}

###

post https://aula-python-fiap-default-rtdb.firebaseio.com/contatos.json HTTP/1.1
Content-Type: application/json

{
    "Nome:":"Maria Silva",
    "Email:":"maria@teste.com",
    "telefone:":"(22) 2222-2222"
}

###

GET https://aula-python-fiap-default-rtdb.firebaseio.com/contatos.json HTTP/1.1

###

DELETE https://aula-python-fiap-default-rtdb.firebaseio.com/contatos/-O6Led3VXmcU0ZUnGKxU.json HTTP/1.1

###

PUT https://aula-python-fiap-default-rtdb.firebaseio.com/contatos/-O6LhoD1WzzkiEGwAJYP.json HTTP/1.1
Content-Type: application/json

{
    "Nome":"João Santos",
    "email":"joao.santos@teste.com",
    "Telefone":"(13)1111-1111"
}